[package]
name = "xdg-desktop-portal-cosmic"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.60"
# ashpd = "0.4.0"
ashpd = { git = "https://github.com/bilelmoussaoui/ashpd" }
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols" }
cosmic-client-toolkit = { git = "https://github.com/pop-os/cosmic-protocols" }
futures = "0.3"
memmap2 = "0.9.0"
# pipewire = { git = "https://github.com/pop-os/pipewire-rs" }
pipewire = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs", features = ["v0_3_33"] }
png = "0.17.5"
rustix = { version = "0.38.0", features = ["fs"] }
serde = "1.0.143"
# spa_sys = { package = "libspa-sys", git = "https://github.com/pop-os/pipewire-rs" }
spa_sys = { package = "libspa-sys", git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
tempfile = "3.5.0"
tokio = { version = "1.19.2", features = ["macros", "net", "rt", "sync"] }
wayland-client = { version = "0.31.1" }
zbus = { version = "3.13.0", default-features = false, features = ["tokio"] }
gbm = "0.13.0"
wayland-protocols = "0.31.0"
