[package]
name = "xdg-desktop-portal-cosmic"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = []
wgpu = ["libcosmic/wgpu"]

[dependencies]
anyhow = "1.0.60"
ashpd = "0.8.1"
cosmic-files = { git = "https://github.com/pop-os/cosmic-files", default-features = false, features = ["wayland"] }
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols", rev = "c8d3a1c" }
cosmic-client-toolkit = { git = "https://github.com/pop-os/cosmic-protocols", rev = "c8d3a1c" }
futures = "0.3"
image = "0.25"
libcosmic = { git = "https://github.com/pop-os/libcosmic", features = [
    "wayland",
    "tokio",
    "dbus-config",
] }
cosmic-bg-config = { git = "https://github.com/pop-os/cosmic-bg" }
memmap2 = "0.9.0"
# pipewire = { git = "https://github.com/pop-os/pipewire-rs" }
once_cell = "1.19.0"
pipewire = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs", features = [
    "v0_3_33",
] }
png = "0.17.5"
rustix = { version = "0.38.0", features = ["fs"] }
serde = "1.0.143"
# spa_sys = { package = "libspa-sys", git = "https://github.com/pop-os/pipewire-rs" }
spa_sys = { package = "libspa-sys", git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
tempfile = "3.5.0"
tokio = { version = "1.19.2", features = ["macros", "net", "rt", "sync"] }
wayland-client = { version = "0.31.1" }
zbus = { version = "4.2.2", default-features = false, features = ["tokio"] }
gbm = "0.15.0"
wayland-protocols = "0.32.1"
env_logger = "0.11.3"
log = "0.4.20"
dirs = "5.0.1"
time = { version = "0.3.31", features = [
    "local-offset",
    "formatting",
    "macros",
] }
url = "2.5"
# i18n
i18n-embed = { version = "0.14.1", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.8.0"
rust-embed = "8.2.0"

[dev-dependencies]
gst = { package = "gstreamer", version = "0.21.3" }

# [patch."https://github.com/pop-os/libcosmic"]
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
#
# [patch."https://github.com/smithay/client-toolkit"]
# sctk = { package = "smithay-client-toolkit", git = "https://github.com/smithay/client-toolkit//", rev = "3bed072" }

[profile.release]
debug = true
