[package]
name = "xdg-desktop-portal-cosmic"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[features]
default = []
wgpu = ["libcosmic/wgpu"]

[workspace]
members = ["cosmic-portal-config"]

[dependencies]
anyhow = "1.0.60"
ashpd = "0.8.1"
cosmic-files = { git = "https://github.com/pop-os/cosmic-files", default-features = false, features = [
    "gvfs",
    "wayland",
] }
cosmic-protocols = { git = "https://github.com/pop-os/cosmic-protocols", rev = "d218c76" }
cosmic-client-toolkit = { git = "https://github.com/pop-os/cosmic-protocols", rev = "d218c76" }
futures = "0.3"
image = "0.25"
libcosmic = { git = "https://github.com/pop-os/libcosmic", features = [
    "autosize",
    "winit",
    "multi-window",
    "desktop",
    "wayland",
    "tokio",
    "dbus-config",
    "wgpu",
] }
cosmic-bg-config = { git = "https://github.com/pop-os/cosmic-bg" }
cosmic-portal-config = { path = "./cosmic-portal-config" }
memmap2 = "0.9.0"
# pipewire = { git = "https://github.com/pop-os/pipewire-rs" }
once_cell = "1.19.0"
pipewire = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs", features = [
    "v0_3_33",
] }
png = "0.17.5"
rustix = { version = "0.38.0", features = ["fs"] }
# spa_sys = { package = "libspa-sys", git = "https://github.com/pop-os/pipewire-rs" }
spa_sys = { package = "libspa-sys", git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
pipewire-sys = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
tempfile = "3.5.0"
tokio = { version = "1.19.2", features = ["macros", "net", "rt", "sync"] }
wayland-client = { version = "0.31.1" }
zbus = { version = "4.2.2", default-features = false, features = ["tokio"] }
gbm = "0.15.0"
wayland-protocols = "0.32.1"
env_logger = "0.11.3"
dirs = "5.0.1"
chrono = "0.4"
url = "2.5"
# i18n
i18n-embed = { version = "0.14.1", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.8.0"
rust-embed = "8.2.0"

# Workspace
cosmic-config.workspace = true
log.workspace = true
serde.workspace = true
freedesktop-desktop-entry = "=0.7.0"

[workspace.dependencies]
cosmic-config = { git = "https://github.com/pop-os/libcosmic" }
log = "0.4.20"
serde = "1.0.143"

[dev-dependencies]
gst = { package = "gstreamer", version = "0.23.0" }
clap = { version = "4.5.9", features = ["derive"] }

# [patch."https://github.com/pop-os/libcosmic"]
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }

# [patch."https://github.com/smithay/client-toolkit"]
# sctk = { package = "smithay-client-toolkit", git = "https://github.com/smithay/client-toolkit//", rev = "3bed072" }

[profile.release]
opt-level = 3
lto = "thin"
