[package]
name = "xdg-desktop-portal-cosmic"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1.0.60"
# pipewire = { git = "https://gitlab.freedesktop.org/pipewire/pipewire-rs" }
pipewire = { git = "https://gitlab.freedesktop.org/ids1024/pipewire-rs", branch = "spa-sys" }
spa_sys = { package = "libspa-sys", git = "https://gitlab.freedesktop.org/ids1024/pipewire-rs", branch = "spa-sys" }
tokio = { version = "1.19.2", features = ["macros", "net", "rt", "sync"] }
zbus = { version = "2.3.2", default-features = false, features = ["tokio"] }
